Repository project-neon/NeonFC, pull requests merged in 2020-10, with the labels that each got.

#13 Created PID initial code
  algorithims/discretizedField.py
  comm/comm.py
  commons/math.py
  config.json
  controller/PID.py
  controller/__init__.py
  entities/Robot.py
  live_plot_script.py
  plot_script.py
  strategy/BaseStrategy.py
  strategy/tests/astarFollowBall.py
  vision/vision.py
Labels: WIP

#16 Potential field
  algorithims/__init__.py
  algorithims/potential_fields/__init__.py
  algorithims/potential_fields/fields.py
  entities/Robot.py
  strategy/tests/__init__.py
  strategy/tests/pfFollowBall.py
  strategy/tests/pfFollowBallLine.py
  strategy/tests/pfGoalKeeper.py
Labels: WIP

#14 Feat/dynamic window approach
  algorithims/__init__.py
  algorithims/dynamicWindowApproach.py
  config.json
  entities/Robot.py
Labels: WIP

#18 Seeing the Pontetial Field [WIP]
  algorithims/potential_fields/fields.py
  comm/comm.py
  commons/math.py
  config.json
  controller/PID.py
  controller/simple_LQR.py
  entities/Robot.py
  enviroment.dev.config
  notebooks/potential_fields_analysis.ipynb
  strategy/tests/__init__.py
  strategy/tests/pfAttacker.py
  strategy/tests/pfFollowBall.py
  strategy/tests/pfGoalKeeper.py
  vision/vision.py
Labels: WIP, enhancement

#21 Add decay to tangential considering zero as radiusline
  algorithims/potential_fields/fields.py
  strategy/tests/Idle.py
Labels: enhancement
