Repository project-neon/NeonFC, pull requests merged in 2021-07, with the labels that each got.

#49 Correção quando implementação de send_replacement nao é feita
  blue_team.json
  main.py
Labels: bug

#50 Base Coach
  config.json
  entities/coach/__init__.py
  entities/coach/coach.py
  entities/coach/experiment_astar.py
  entities/coach/iron2021.py
  entities/coach/larc2020.py
  match/match.py
  yellow_team.json
Labels: enhancement

#51 Implementação de transições para bolas paradas no playbook
  entities/coach/iron2021.py
  entities/plays/__init__.py
  entities/plays/playbook.py
  main.py
Labels: WIP, enhancement
