Repository project-neon/NeonFC, pull requests merged in 2021-06, with the labels that each got.

#45 Implementação do algoritmo A*
  algorithims/a_star/__init__.py
  algorithims/a_star/astar.py
  algorithims/a_star/fieldGraph.py
Labels: enhancement

#47 Applied astar algorithm on voronoi heuristic example & Fix path module for astar
  algorithims/a_star/__init__.py
  algorithms/__init__.py
  algorithms/astar.py
  algorithms/astar/__init__.py
  algorithms/astar/astar.py
  algorithms/astar/fieldGraph.py
  algorithms/discretizedField.py
  algorithms/dwa/dynamicWindowApproach.py
  algorithms/potential_fields/fields.py
  strategy/tests/__init__.py
  strategy/tests/asScratch.py
  strategy/tests/dwaScratch.py
Labels: bug

#48 feat/positions
  config.json
  entities/coach/larc2020.py
  foul_placements.json
  main.py
Labels: WIP, enhancement
